# Generated by Django 4.1.2 on 2022-10-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='slackUsername',
        ),
    ]
